-- Hub Central CHC - estructura MySQL
-- Ejecutar primero: mysql -u root -p < sql/01_schema.sql

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS hubcentral_chc
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE hubcentral_chc;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS extensions;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(80) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(160) NOT NULL DEFAULT '',
  role ENUM('admin') NOT NULL DEFAULT 'admin',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE locations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  branch_number INT UNSIGNED NULL,
  store_type VARCHAR(20) NOT NULL DEFAULT 'HC',
  name VARCHAR(180) NOT NULL,
  municipality VARCHAR(140) NOT NULL DEFAULT '',
  maps_url VARCHAR(500) NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Activa',
  is_pending TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_locations_branch_number (branch_number),
  KEY idx_locations_name (name),
  KEY idx_locations_municipality (municipality),
  KEY idx_locations_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE extensions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  extension VARCHAR(20) NOT NULL,
  first_name VARCHAR(120) NOT NULL DEFAULT '',
  last_name VARCHAR(120) NOT NULL DEFAULT '',
  display_name VARCHAR(180) NOT NULL DEFAULT '',
  office_location VARCHAR(120) NOT NULL DEFAULT '',
  phone_model VARCHAR(120) NOT NULL DEFAULT '',
  type ENUM('OFICINA','SUCURSAL','PANADERIA','VIGILANCIA','SIN TIPO') NOT NULL DEFAULT 'SIN TIPO',
  location_id INT UNSIGNED NULL,
  is_visible TINYINT(1) NOT NULL DEFAULT 1,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_extensions_extension (extension),
  KEY idx_extensions_type (type),
  KEY idx_extensions_visible (is_visible),
  KEY idx_extensions_location_id (location_id),
  CONSTRAINT fk_extensions_location
    FOREIGN KEY (location_id) REFERENCES locations(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Hub Central CHC - poblar ubicaciones
-- Se usan los enlaces de Google Maps compartidos; este seed no depende de coordenadas.

SET NAMES utf8mb4;
USE hubcentral_chc;

DELETE FROM locations;

INSERT INTO locations
  (id, branch_number, store_type, name, municipality, maps_url, status, is_pending, is_active, notes)
VALUES
  (1, 1, 'HC', 'Abastos', 'Querétaro', 'https://maps.app.goo.gl/dDL8HcPvFxK6qACQ6', 'Activa', 0, 1, NULL),
  (2, 2, 'HC', 'Carrillo', 'Querétaro', 'https://maps.app.goo.gl/b5We3ZAkcW82Sybf7', 'Activa', 0, 1, NULL),
  (3, 3, 'HC', 'Sauces', 'Querétaro', 'https://maps.app.goo.gl/3vo2RKxqXxsdKdQ97', 'Activa', 0, 1, NULL),
  (4, 4, 'HC', 'Presidentes', 'Querétaro', 'https://maps.app.goo.gl/mR3859iWoC9uupyp7', 'Activa', 0, 1, NULL),
  (5, 5, 'HC', 'San Roque', 'Querétaro', 'https://maps.app.goo.gl/4XjjshWSaiJ68kgs9', 'Activa', 0, 1, NULL),
  (6, 6, 'HC', 'Satelite', 'Querétaro', 'https://maps.app.goo.gl/MafEGGf2djKBkGaQ9', 'Activa', 0, 1, NULL),
  (7, 7, 'HC', 'Plazas del Sol', 'Querétaro', 'https://maps.app.goo.gl/QqZpuiaZXJYfwE1UA', 'Activa', 0, 1, NULL),
  (8, 8, 'HC', 'Pie de la cuesta 1', 'Querétaro', 'https://maps.app.goo.gl/ZVNMPNjGwLtaGLPm8', 'Activa', 0, 1, NULL),
  (9, 9, 'HC', 'Lomas del Marqués', 'Querétaro', 'https://maps.app.goo.gl/69996JWu3QjMkZDV6', 'Activa', 0, 1, NULL),
  (10, 10, 'HC', 'Cerrito Colorado', 'Querétaro', 'https://maps.app.goo.gl/baKpvGL4bEnM7q137', 'Activa', 0, 1, NULL),
  (11, 11, 'HC', 'Andadores', 'Querétaro', 'https://maps.app.goo.gl/yECTzBpzXZLsntJo9', 'Activa', 0, 1, NULL),
  (12, 12, 'HC', 'Reforma Agraria', 'Querétaro', 'https://maps.app.goo.gl/ircjPvYJHqRCNGSMA', 'Activa', 0, 1, NULL),
  (13, 13, 'HC', 'Tintero 1', 'Querétaro', 'https://maps.app.goo.gl/ZJ6s1dD7izuuSY4N8', 'Activa', 0, 1, NULL),
  (14, 14, 'HC', 'Tejeda 1', 'Corregidora', 'https://maps.app.goo.gl/ks24XL6kT1umV7st6', 'Activa', 0, 1, NULL),
  (15, 15, 'HC', 'Satelite 2', 'Querétaro', 'https://maps.app.goo.gl/H1NvfVg7qkKN1hV28', 'Activa', 0, 1, NULL),
  (16, 16, 'HC', 'Ensueño', 'Querétaro', 'https://maps.app.goo.gl/VmGVPMG5bRRcWDBB8', 'Activa', 0, 1, NULL),
  (17, 17, 'HC', 'Candiles 1', 'Corregidora', 'https://maps.app.goo.gl/uuEfC5axWFDUm2dn7', 'Activa', 0, 1, NULL),
  (18, 18, 'HC', 'Cerrito Colorado 2', 'Querétaro', 'https://maps.app.goo.gl/kBJskpWz4bFGuBam9', 'Activa', 0, 1, NULL),
  (19, 19, 'HC', 'Tejeda 2', 'Corregidora', 'https://maps.app.goo.gl/krc1MZEFUdvfh5426', 'Activa', 0, 1, NULL),
  (20, 20, 'HC', 'Pie de la cuesta 2', 'Querétaro', 'https://maps.app.goo.gl/kdT9kEyT63nPQvFE8', 'Activa', 0, 1, NULL),
  (21, 21, 'HC', 'Paseo San Miguel', 'Querétaro', 'https://maps.app.goo.gl/5yJGhKBsheP3MbS59', 'Activa', 0, 1, NULL),
  (22, 22, 'HC', 'La pradera 2', 'El Marqués', 'https://maps.app.goo.gl/QxsaGmPa3vNyrtHV9', 'Activa', 0, 1, NULL),
  (23, 23, 'HC', 'Loarca', 'Querétaro', 'https://maps.app.goo.gl/kh78LgTuaFy2GgCz8', 'Activa', 0, 1, NULL),
  (24, 24, 'HC', 'San Miguel de Allende 1', 'San Miguel Allende', 'https://maps.app.goo.gl/74zSHRm1G5joSPqK8', 'Activa', 0, 1, NULL),
  (25, 25, 'HC', 'San Juan de Letrán', 'Querétaro', 'https://maps.app.goo.gl/DeJxcBoyC3SuFui9A', 'Activa', 0, 1, NULL),
  (26, 26, 'HC', 'Cerrito Colorado 3', 'Querétaro', 'https://maps.app.goo.gl/RveQYBHRxpLJJefA6', 'Activa', 0, 1, NULL),
  (27, 27, 'HC', 'San Pablo', 'Querétaro', 'https://maps.app.goo.gl/H45uxbaBR11HAfBe9', 'Activa', 0, 1, NULL),
  (28, 28, 'HC', 'La Pradera 1', 'El Marqués', 'https://maps.app.goo.gl/5Em7mZiTPePjwAQXA', 'Activa', 0, 1, NULL),
  (29, 29, 'HC', 'Campo Militar', 'Querétaro', 'https://maps.app.goo.gl/14c63nWwxGqYR9Ga8', 'Activa', 0, 1, NULL),
  (30, 30, 'HC', 'Hacienda la cruz', 'El Marqués', 'https://maps.app.goo.gl/BxhxKpVpqUYbkcsc8', 'Activa', 0, 1, NULL),
  (31, 31, 'HC', 'Miranda', 'El Marqués', 'https://maps.app.goo.gl/bFnrAyoYHkDD5LV18', 'Activa', 0, 1, NULL),
  (32, 32, 'MC', 'El Mirador', 'El Marqués', 'https://maps.app.goo.gl/9MYxa4wr2vwucY7x8', 'Activa', 0, 1, NULL),
  (33, 33, 'HC', 'Insurgentes', 'Querétaro', 'https://maps.app.goo.gl/tYVrPLuk3pTxpUfY6', 'Activa', 0, 1, NULL),
  (34, 34, 'HC', 'Paseos del Pedregal', 'Querétaro', 'https://maps.app.goo.gl/rC5UhiACmWXxUg5p7', 'Activa', 0, 1, NULL),
  (35, 35, 'HC', 'Juriquilla 1', 'Querétaro', 'https://maps.app.goo.gl/M8hc3bEHBRSDExCv9', 'Activa', 0, 1, NULL),
  (36, 36, 'HC', 'Real de la Loma', 'Querétaro', 'https://maps.app.goo.gl/UNGemGQEbtb62i9T9', 'Activa', 0, 1, NULL),
  (37, 37, 'HC', 'Av de la luz', 'Querétaro', 'https://maps.app.goo.gl/yNwSbCQkrT9NxN8S6', 'Activa', 0, 1, NULL),
  (38, 38, 'HC', 'Viñedos', 'Querétaro', 'https://maps.app.goo.gl/arZdz9vttxzzKioT9', 'Activa', 0, 1, NULL),
  (39, 39, 'HC', 'Santa María', 'Querétaro', 'https://maps.app.goo.gl/JUaVamRftQzoTUURA', 'Activa', 0, 1, NULL),
  (40, 40, 'HC', 'Tintero 2 ( Ex hacienda tintero )', 'Querétaro', 'https://maps.app.goo.gl/N4az5tEuZJ2ASS7y6', 'Activa', 0, 1, NULL),
  (41, 41, 'HC', 'El Refugio 1', 'Querétaro', 'https://maps.app.goo.gl/VTjegxkpQNv3vrBc6', 'Activa', 0, 1, NULL),
  (42, 42, 'HC', 'Villas de Santiago', 'Querétaro', 'https://maps.app.goo.gl/eZ1y3ZBj2jLbWf8v5', 'Activa', 0, 1, NULL),
  (43, 43, 'HC', 'Ciudad del Sol', 'Querétaro', 'https://maps.app.goo.gl/abfhH2QSvCeGUm6H9', 'Activa', 0, 1, NULL),
  (44, 44, 'HC', 'Milenio', 'Querétaro', 'https://maps.app.goo.gl/8azbznYKAhzrz9CR7', 'Activa', 0, 1, NULL),
  (45, 45, 'HC', 'Prol Pasteur', 'Querétaro', 'https://maps.app.goo.gl/x7My78cWL8gwPTNw8', 'Activa', 0, 1, NULL),
  (46, 46, 'HC', 'Sonterra', 'Querétaro', 'https://maps.app.goo.gl/RAMDqLxXn1XwzNGy8', 'Activa', 0, 1, NULL),
  (47, 47, 'HC', 'Valle Diamante', 'Corregidora', 'https://maps.app.goo.gl/9wkvukrBb8AYGcap8', 'Activa', 0, 1, NULL),
  (48, 48, 'HC', 'Valle de Santiago', 'Querétaro', 'https://maps.app.goo.gl/5oeybsSr8Rs8oFCG9', 'Activa', 0, 1, NULL),
  (49, 49, 'HC', 'Sauces 2', 'Querétaro', 'https://maps.app.goo.gl/JTbycfr2kFCPekdY7', 'Activa', 0, 1, NULL),
  (50, 50, 'HC', 'Vista Real', 'Corregidora', 'https://maps.app.goo.gl/wb22nGFh3BUgmKMh8', 'Activa', 0, 1, NULL),
  (51, 51, 'HC', 'Los Héroes', 'El Marqués', 'https://maps.app.goo.gl/PT1Nr8edBjrwSkgZ7', 'Activa', 0, 1, NULL),
  (52, 52, 'HC', 'Rincones del Marqués', 'El Marqués', 'https://maps.app.goo.gl/SRoQPnVHWKLTQqUq6', 'Activa', 0, 1, NULL),
  (53, 53, 'HC', 'Puerta Verona', 'Querétaro', 'https://maps.app.goo.gl/KbtKVRaZmWuXgoiP8', 'Activa', 0, 1, NULL),
  (54, 54, 'HC', 'Real Solare', 'El Marqués', 'https://maps.app.goo.gl/w8Y3tmT34sUjtY119', 'Activa', 0, 1, NULL),
  (55, 55, 'HC', 'Ciudad del Sol 2', 'Querétaro', 'https://maps.app.goo.gl/Y1XEh6DL93ixqYCK6', 'Activa', 0, 1, NULL),
  (56, 56, 'HC', 'Santuario', 'Corregidora', 'https://maps.app.goo.gl/gjsodumxetbug6Ac6', 'Activa', 0, 1, NULL),
  (57, 57, 'HC', 'Los Olvera', 'Corregidora', 'https://maps.app.goo.gl/414YsCvuoxKfPbkSA', 'Activa', 0, 1, NULL),
  (58, 58, 'HC', 'Real del Bosque', 'Corregidora', 'https://maps.app.goo.gl/DiVzXBEMVmb8ZYvQ9', 'Activa', 0, 1, NULL),
  (59, 59, 'HC', 'Alcanfores', 'Querétaro', 'https://maps.app.goo.gl/Ty2GwUtTyMLVPgRMA', 'Activa', 0, 1, NULL),
  (60, 60, 'HC', 'San Miguel de Allende 2', 'San Miguel Allende', 'https://maps.app.goo.gl/E4vchv9gk9RD9tgi7', 'Activa', 0, 1, NULL),
  (61, 61, 'HC', 'San Isidro', 'Querétaro', 'https://maps.app.goo.gl/X3prNJoZtbVHetfH6', 'Activa', 0, 1, NULL),
  (62, 62, 'MC', 'Plaza Atelier', 'Querétaro', 'https://maps.app.goo.gl/bSo43CQqGpfdr5bR7', 'Activa', 0, 1, NULL),
  (63, 63, 'HC', 'Tecnologico', 'Querétaro', 'https://maps.app.goo.gl/kSTzP2X3yugh7p2a8', 'Activa', 0, 1, NULL),
  (64, 64, 'HC', 'Candiles 2', 'Corregidora', 'https://maps.app.goo.gl/PPXAEfA6ZCcFyizA8', 'Activa', 0, 1, NULL),
  (65, 65, 'HC', 'El Refugio 2', 'Querétaro', 'https://maps.app.goo.gl/k2DbbbkBgx4ENSQJ8', 'Activa', 0, 1, NULL),
  (66, 66, 'HC', 'Jacal', 'Corregidora', 'https://maps.app.goo.gl/UUu4YgHaGcoJ3PC2A', 'Activa', 0, 1, NULL),
  (67, 67, 'HC', 'Jardines de la hacienda', 'Querétaro', 'https://maps.app.goo.gl/kk2uff7U9Efdypu98', 'Activa', 0, 1, NULL),
  (68, 68, 'HC', 'Av del sol', 'Querétaro', 'https://maps.app.goo.gl/7J8yCncrWhqomXrn6', 'Activa', 0, 1, NULL),
  (69, 69, 'HC', 'Plaza Candiles', 'Corregidora', 'https://maps.app.goo.gl/yJduHX5EbW2EfM396', 'Activa', 0, 1, NULL),
  (70, 70, 'HC', 'Los huertos', 'Querétaro', 'https://maps.app.goo.gl/hr1x4h2PokiTnYSZ6', 'Activa', 0, 1, NULL),
  (71, 71, 'HC', 'Av Cimatario', 'Querétaro', 'https://share.google/uWBjtvKQVwiMIcS8Y', 'Activa', 0, 1, NULL),
  (72, 72, 'HC', 'Platón', 'Querétaro', 'https://maps.app.goo.gl/UYP7qGgLkYNMAqWLA', 'Activa', 0, 1, NULL),
  (73, 73, 'HC', 'Piramides', 'Corregidora', 'https://maps.app.goo.gl/zZXaQbGNjQAeKEuA7', 'Activa', 0, 1, NULL),
  (74, 74, 'MC', 'Zibata 1', 'El Marqués', 'https://maps.app.goo.gl/F4pRHM6TGjvbjH5k8', 'Activa', 0, 1, NULL),
  (75, 75, 'HC', 'Juriquilla 2', 'Querétaro', 'https://maps.app.goo.gl/Ko2ARVWhLYuNQLGz6', 'Activa', 0, 1, NULL),
  (76, 76, 'MC', 'Zakia', 'El Marqués', 'https://maps.app.goo.gl/6f6bFsvzfyDPHKCEA', 'Activa', 0, 1, NULL),
  (77, 77, 'HC', 'Puerta Navarra', 'Querétaro', 'https://maps.app.goo.gl/xFd4AQjVmJWXctWp8', 'Activa', 0, 1, NULL),
  (78, 78, 'HC', 'Pedro Escobedo', 'Pedro Escobedo', 'https://maps.app.goo.gl/svrpqisjUtpWTghh8', 'Activa', 0, 1, NULL),
  (79, 79, 'HC', 'Geo plazas', 'Querétaro', 'https://maps.app.goo.gl/xW9VseDQiyooSSuAA', 'Activa', 0, 1, NULL),
  (80, 80, 'HC', 'Candiles 3', 'Corregidora', 'https://maps.app.goo.gl/i6GnqAkwj73UfxY48', 'Activa', 0, 1, NULL),
  (81, 81, 'HC', 'Palmares', 'Querétaro', 'https://maps.app.goo.gl/Tar4zuQRwSuMCvPq7', 'Activa', 0, 1, NULL),
  (82, 82, 'HC', 'Pedro Escobedo 2', 'Pedro Escobedo', 'https://maps.app.goo.gl/5A8xtX7nkFeYh5Mx9', 'Activa', 0, 1, NULL),
  (83, 83, 'HC', 'Plaza Belén', 'Querétaro', 'https://maps.app.goo.gl/dQUFAQrjLTSvhCD27', 'Activa', 0, 1, NULL),
  (84, 84, 'HC', 'Fuentes de Balvanera', 'Apaseo el Grande', 'https://maps.app.goo.gl/DGRgXZxjnRR1ZmccA', 'Activa', 0, 1, NULL),
  (85, 85, 'HC', 'El Refugio 3', 'Querétaro', 'https://maps.app.goo.gl/HRfdyKWkr2qwLMuP6', 'Activa', 0, 1, NULL),
  (86, 86, 'HC', 'La Gloria', 'Querétaro', 'https://maps.app.goo.gl/uA4k61Jyb8t4ZZbT6', 'Activa', 0, 1, NULL),
  (87, 87, 'HC', 'San Miguel de Allende 3', 'San Miguel Allende', 'https://maps.app.goo.gl/roEyD489qcqVxphX8', 'Activa', 0, 1, NULL),
  (88, 88, 'HC', 'Real de San Isidro San Juan del Río', 'San Juan del Río', 'https://maps.app.goo.gl/jH2guewiY7iMckuY9', 'Activa', 0, 1, NULL),
  (89, 89, 'HC', 'El pueblito', 'Corregidora', 'https://maps.app.goo.gl/x9SQrYrhGHkRN2fWA', 'Activa', 0, 1, NULL),
  (90, 90, 'HC', 'Sombrerete', 'Querétaro', 'https://maps.app.goo.gl/8RMavPazYtZ721fD7', 'Activa', 0, 1, NULL),
  (91, 91, 'HC', 'Plaza Naciones', 'Querétaro', 'https://maps.app.goo.gl/oa8sQrRzQYmfaQnf7', 'Activa', 0, 1, NULL),
  (92, 92, 'HC', 'Lomas Calle 27', 'Querétaro', 'https://maps.app.goo.gl/NRGg4LqKMN63ncWk6', 'Activa', 0, 1, NULL),
  (93, 93, 'HC', 'Niños Héroes', 'Querétaro', 'https://maps.app.goo.gl/9XGLoij5TvDmFNVw6', 'Activa', 0, 1, NULL),
  (94, 94, 'HC', 'La negreta', 'Corregidora', 'https://maps.app.goo.gl/2Dc4tTS6sZEBjmSu8', 'Activa', 0, 1, NULL),
  (95, 95, 'HC', 'Villas del Refugio', 'El Marqués', 'https://maps.app.goo.gl/WntGWX7HYKnpfjX98', 'Activa', 0, 1, NULL),
  (96, 96, 'MC', 'Zibata 2', 'El Marqués', 'https://maps.app.goo.gl/ccGefjr5aoCVmj1q6', 'Activa', 0, 1, NULL),
  (97, 97, 'HC', 'San Miguel de Allende 4', 'San Miguel Allende', 'https://maps.app.goo.gl/ZCQ3f88fYjPvdTiS9', 'Activa', 0, 1, NULL),
  (98, 98, 'HC', 'Loma Bonita', 'Querétaro', 'https://maps.app.goo.gl/TeQroH5nUGpgMifDA', 'Activa', 0, 1, NULL),
  (99, 99, 'HC', 'Menchaca', 'Querétaro', 'https://maps.app.goo.gl/t6SrKqvwgeHu5sPX6', 'Activa', 0, 1, NULL),
  (100, 100, 'HC', 'Burócrata', 'Querétaro', 'https://maps.app.goo.gl/9CYfmxoh4osomwai6', 'Activa', 0, 1, NULL),
  (101, 101, 'HC', 'Milenio #100', 'Querétaro', 'https://maps.app.goo.gl/xDKmDD2b8mWFKWNH9', 'Activa', 0, 1, NULL),
  (102, 102, 'HC', 'Lomas Calle 25', 'Querétaro', 'https://maps.app.goo.gl/hRjVZijeNyCjZbbi9', 'Activa', 0, 1, NULL),
  (104, 104, 'HC', 'Privada Juriquilla', 'Querétaro', 'https://maps.app.goo.gl/tvdiPUfNidutnMrz8', 'Activa', 0, 1, NULL),
  (105, 105, 'HC', 'Colinas del Sol', 'Corregidora', 'https://maps.app.goo.gl/ugFwdNh8GyGwCEsd7', 'Activa', 0, 1, NULL),
  (106, 106, 'HC', 'La popular', 'Querétaro', 'https://maps.app.goo.gl/C4CWeTerXud3ifcz7', 'Activa', 0, 1, NULL),
  (107, 107, 'HC', 'Santa Fe', 'Querétaro', 'https://maps.app.goo.gl/o6kofCYJUb3PqcRZ7', 'Activa', 0, 1, NULL),
  (108, 108, 'HC', 'Cimatario Panteón', 'Querétaro', 'https://maps.app.goo.gl/NdvDGZFCaZBktSvC9', 'Activa', 0, 1, NULL),
  (109, 109, 'HC', 'Corregidora Centro', 'Querétaro', 'https://maps.app.goo.gl/2J9ymN1Kq9SfCh3v5', 'Activa', 0, 1, NULL),
  (110, 110, 'HC', 'San Juan del Río 2 El Roble', 'San Juan del Río', 'https://maps.app.goo.gl/Wta1bnsjFFGrbxoj7', 'Activa', 0, 1, NULL),
  (111, 111, 'HC', 'El Condado', 'Corregidora', 'https://maps.app.goo.gl/EppaBVzNuarvKkgy5', 'Activa', 0, 1, NULL),
  (112, 112, 'HC', 'El Rocío', 'Querétaro', 'https://maps.app.goo.gl/2m4C2FxuRMaAK4USA', 'Activa', 0, 1, NULL),
  (113, 113, 'HC', 'Pueblo de Jurica', 'Querétaro', 'https://maps.app.goo.gl/7sCtmi2kGVJPE3gVA', 'Activa', 0, 1, NULL),
  (114, 114, 'MC', 'Zakia Zizana', 'El Marqués', 'https://maps.app.goo.gl/XoSwnpnLvEpC9Pc1A', 'Activa', 0, 1, NULL),
  (115, 115, 'HC', 'Ejido San Miguel', 'Querétaro', 'https://maps.app.goo.gl/Ua1qbJ9SCdzPed297', 'Activa', 0, 1, NULL),
  (116, 116, 'HC', 'El marqués queretano', 'Querétaro', 'https://maps.app.goo.gl/CEAdCrMtAh1ZyL8C7', 'Activa', 0, 1, NULL),
  (117, 117, 'HC', 'Loarca 2', 'Querétaro', 'https://maps.app.goo.gl/xPQsGh6BbqgM1DS79', 'Activa', 0, 1, NULL),
  (118, 118, 'HC', 'San Jose el alto 1', 'Querétaro', 'https://maps.app.goo.gl/AP52YHsMBrcLiyCh8', 'Activa', 0, 1, NULL),
  (119, 119, 'HC', 'SJR - Las Aguilas', 'San Juan del Río', 'https://maps.app.goo.gl/zZ7az4RRtgZrrL8K8', 'Activa', 0, 1, NULL),
  (120, 120, 'HC', 'Cd del sol - Plaza Rioma', 'Querétaro', 'https://maps.app.goo.gl/jaLPxAVZFhqCQZYG7', 'Activa', 0, 1, NULL),
  (121, 121, 'HC', 'El Salitre', 'Querétaro', 'https://maps.app.goo.gl/njQ9eM4SWbVbGpS8A', 'Activa', 0, 1, NULL),
  (122, 122, 'HC', 'Reforma Deportiva', 'Querétaro', 'https://maps.app.goo.gl/vHDrnoywDfrEJMov9', 'Activa', 0, 1, NULL),
  (125, 125, 'HC', 'Villas de Santiago 2', 'Querétaro', 'https://maps.app.goo.gl/vAP9i83RoDvXcfus6', 'Activa', 0, 1, NULL),
  (1001, NULL, 'HC', 'Fuentes de Balvanera 2', 'Apaseo el Grande', NULL, 'En tramite', 1, 1, 'Sucursal pendiente importada desde la página de ubicaciones.'),
  (1002, NULL, 'HC', 'La lira', 'Pedro Escobedo', NULL, 'No abierta', 1, 1, 'Sucursal pendiente importada desde la página de ubicaciones.');

ALTER TABLE locations AUTO_INCREMENT = 1003;


-- Hub Central CHC - poblar extensiones
-- Ejecutar después de 01_schema.sql y 02_seed_locations.sql.

SET NAMES utf8mb4;
USE hubcentral_chc;

DELETE FROM extensions;

INSERT INTO extensions
  (extension, first_name, last_name, display_name, office_location, phone_model, type, location_id, is_visible, notes)
VALUES
  ('10', 'Vacante 1', '', 'Vacante 1', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('11', 'Vacante 2', '', 'Vacante 2', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('12', 'Vacante 3', '', 'Vacante 3', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('13', 'Vacante 4', '', 'Vacante 4', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('14', 'Vacante 5', '', 'Vacante 5', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('16', 'Vacante 6', '', 'Vacante 6', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('17', 'Vacante 7', '', 'Vacante 7', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('100', 'EDITH', 'Vargas', 'Recepcion', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('101', 'OSCAR', 'Aguilar', 'Contador', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('102', 'Georgina', 'Ramirez', 'Reclutamiento', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('103', 'BRENDA', 'Hernandez', 'Finanzas', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('104', 'ELIZABETH', 'Sanchez', 'Activo Fijo', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('105', 'LORENA', 'Mata', 'Compras', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('106', 'PAULINA', 'Paredes', 'CXP', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('107', 'ANDRES', 'Mendoza', 'Capital Humano', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('108', 'Rodrigo', 'Quintanilla', 'Rodrigo Quintanilla', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('109', 'FERNANDO', 'Flores', 'Fernando', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('110', 'MARISA', 'Quintanilla', 'Director', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('111', 'Erika', 'Distribucion', 'Cedis', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('112', 'VENTAS', 'Coronel', 'Ventas', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('113', 'ESPERANZA', 'Gonzalez', 'Esperanza', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('114', 'Jorge', 'Duque', 'Jorge Duque', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('115', 'Sin extension', '', '', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('116', 'SAN JUAN LETRAN', 'Coronel', 'SAN JUAN LETRAN', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('117', 'Sin servicio', '', '', 'QRO', 'CP-6821', 'SIN TIPO', NULL, 0, NULL),
  ('118', 'CRISTINA', 'Zamudio', 'Cristina', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('119', 'ADALBERTO', 'Beltran', 'Adal', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('120', 'ITZEL', 'Hernandez', 'Itzel', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('121', 'VENTAS', 'Coronel', 'Ventas', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('122', 'PANADERIA', 'Coronel', 'Panaderia', 'QRO', 'CP-6821', 'PANADERIA', NULL, 1, NULL),
  ('124', 'JUANA ELIZABETH', 'Velazquez', 'Juanita', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('126', 'CERRITO COLORADO 3', 'Coronel', 'CERRITO COLORADO 3', 'QRO', 'CP-6821', 'SUCURSAL', 26, 1, NULL),
  ('129', 'IDALIA', 'Hernandez', 'Idalia', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('130', 'SISTEMAS', 'Cervantes', 'Sistemas', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('132', 'Mercadotecnia', 'Escobar', 'Ernesto', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('133', 'ELVIA', 'Chavez', 'Elvia', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('134', 'CEDIS', 'Coronel', 'Rosy', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('135', 'PACO', 'Coronel', 'Francisco', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('136', 'Compras', 'Coronel', 'Compras', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('137', 'VIGILANTE', 'Coronel', 'Vigilancia', 'QRO', 'CP-6821', 'VIGILANCIA', NULL, 1, NULL),
  ('138', 'CARMEN', 'Ramirez', 'Carmen', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('139', 'Paola', 'Reclutamiento', 'RH', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('141', 'Miguel Sinecio', 'Humanos', 'RH', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('142', 'Mantenimiento', 'Aviña', 'Reyna', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('143', 'Capacitacion', 'Humanos', 'RH', 'QRO', 'CP-6821', 'OFICINA', NULL, 1, NULL),
  ('201', 'ABASTOS', 'Coronel', 'ABASTOS', 'QRO', 'CP-6821', 'SUCURSAL', 1, 1, NULL),
  ('202', 'ABASTOS 2', 'Coronel', 'ABASTOS 2', 'QRO', 'CP-6821', 'SUCURSAL', 25, 1, NULL),
  ('203', 'SATELITE 1', 'Coronel', 'SATELITE 1', 'QRO', 'CP-6821', 'SUCURSAL', 6, 1, NULL),
  ('204', 'CARRILLO', 'Coronel', 'CARRILLO', 'QRO', 'CP-6821', 'SUCURSAL', 2, 1, NULL),
  ('206', 'PRESIDENTES', 'Coronel', 'PRESIDENTES', 'QRO', 'CP-6821', 'SUCURSAL', 4, 1, NULL),
  ('207', 'SAN ROQUE', 'Coronel', 'SAN ROQUE', 'QRO', 'CP-6821', 'SUCURSAL', 5, 1, NULL),
  ('209', 'SAUCES', 'Coronel', 'SAUCES', 'QRO', 'CP-6821', 'SUCURSAL', 3, 1, NULL),
  ('210', 'PLAZAS DEL SOL', 'Coronel', 'PLAZAS', 'QRO', 'CP-6821', 'SUCURSAL', 7, 1, NULL),
  ('212', 'LOMAS DEL MARQUES', 'Coronel', 'LOMAS DEL MARQUES', 'QRO', 'CP-6821', 'SUCURSAL', 9, 1, NULL),
  ('213', 'PIE CUESTA 1', 'Coronel', 'PIE CUESTA 1', 'QRO', 'CP-6821', 'SUCURSAL', 8, 1, NULL),
  ('215', 'CERRITO COLORADO 1', 'Coronel', 'CERRITO COLORADO 1', 'QRO', 'CP-6821', 'SUCURSAL', 10, 1, NULL),
  ('216', 'PASEOS DE SAN MIGUEL', 'Coronel', 'SAN MIGUEL', 'QRO', 'CP-6821', 'SUCURSAL', 21, 1, NULL),
  ('217', 'ANDADORES', 'Coronel', 'ANDADORES', 'QRO', 'CP-6821', 'SUCURSAL', 11, 1, NULL),
  ('218', 'REF AGRARIA', 'Coronel', 'REF AGRARIA', 'QRO', 'CP-6821', 'SUCURSAL', 12, 1, NULL),
  ('219', 'TEJEDA 1', 'Coronel', 'TEJEDA 1', 'QRO', 'CP-6821', 'SUCURSAL', 14, 1, NULL),
  ('220', 'SATELITE 2', 'Coronel', 'SATELITE 2', 'QRO', 'CP-6821', 'SUCURSAL', 15, 1, NULL),
  ('221', 'ENSUEÑO', 'Coronel', 'ENSUEÑO', 'QRO', 'CP-6821', 'SUCURSAL', 16, 1, NULL),
  ('222', 'CANDILES', 'Coronel', 'CANDILES', 'QRO', 'CP-6821', 'SUCURSAL', 17, 1, NULL),
  ('223', 'TINTERO', 'Coronel', 'TINTERO', 'QRO', 'CP-6821', 'SUCURSAL', 13, 1, NULL),
  ('224', 'CERRITO COL 2', 'Coronel', 'CERRITO COL 2', 'QRO', 'CP-6821', 'SUCURSAL', 18, 1, NULL),
  ('225', 'TEJEDA 2', 'Coronel', 'TEJEDA 2', 'QRO', 'CP-6821', 'SUCURSAL', 19, 1, NULL),
  ('226', 'Pie de la Cuesta 2', 'Coronel', 'Pie De La Cuesta II', 'QRO', 'CP-6821', 'SUCURSAL', 20, 1, NULL),
  ('227', 'SAN PABLO', 'Coronel', 'SAN PABLO', 'QRO', 'CP-6821', 'SUCURSAL', 27, 1, NULL),
  ('228', 'PRADERA 1', 'Coronel', 'PRADERA 1', 'QRO', 'CP-6821', 'SUCURSAL', 28, 1, NULL),
  ('229', 'PRADERA 2', 'Coronel', 'PRADERA 2', 'QRO', 'CP-6821', 'SUCURSAL', 22, 1, NULL),
  ('230', 'LOARCA', 'Coronel', 'LOARCA', 'QRO', 'CP-6821', 'SUCURSAL', 23, 1, NULL),
  ('231', 'SAN MIGUEL ALLENDE', 'Coronel', 'SAN MIGUEL ALLENDE', 'QRO', 'CP-6821', 'SUCURSAL', 24, 1, NULL),
  ('234', 'HACIENDA LA CRUZ', 'Coronel', 'HACIENDA LA CRUZ', 'QRO', 'CP-6821', 'SUCURSAL', 30, 1, NULL),
  ('235', 'CAMPO MILITAR', 'Coronel', 'CAMPO MILITAR', 'QRO', 'CP-6821', 'SUCURSAL', 29, 1, NULL),
  ('236', 'EL MIRADOR', 'Coronel', 'EL MIRADOR', 'QRO', 'CP-6821', 'SUCURSAL', 32, 1, NULL),
  ('237', 'MIRANDA', 'Coronel', 'MIRANDA', 'QRO', 'CP-6821', 'SUCURSAL', 31, 1, NULL),
  ('238', 'INSURGENTES', 'Coronel', 'INSURGENTES', 'QRO', 'CP-6821', 'SUCURSAL', 33, 1, NULL),
  ('239', 'PEDREGAL', 'Coronel', 'PEDREGAL', 'QRO', 'CP-6821', 'SUCURSAL', 34, 1, NULL),
  ('240', 'Viñedos', 'Coronel', 'Viñedos', 'QRO', 'CP-6821', 'SUCURSAL', 38, 1, NULL),
  ('241', 'JURIQUILLA', 'Coronel', 'JURIQUILLA', 'QRO', 'CP-6821', 'SUCURSAL', 35, 1, NULL),
  ('242', 'REAL DE LA LOMA', 'Coronel', 'REAL DE LA LOMA', 'QRO', 'CP-6821', 'SUCURSAL', 36, 1, NULL),
  ('244', 'AV DE LA LUZ', 'Coronel', 'AV DE LA LUZ', 'QRO', 'CP-6821', 'SUCURSAL', 37, 1, NULL),
  ('245', 'STA MARIA', 'Coronel', 'STA MARIA', 'QRO', 'CP-6821', 'SUCURSAL', 39, 1, NULL),
  ('246', 'EX HDA TINTERO', 'Coronel', 'EX HDA TINTERO', 'QRO', 'CP-6821', 'SUCURSAL', 40, 1, NULL),
  ('247', 'REFUGIO', 'Coronel', 'REFUGIO', 'QRO', 'CP-6821', 'SUCURSAL', 41, 1, NULL),
  ('248', 'VILLAS DE SANTIAGO', 'Coronel', 'VILLAS DE SANTIAGO', 'QRO', 'CP-6821', 'SUCURSAL', 42, 1, NULL),
  ('249', 'SONTERRA', 'Coronel', 'SONTERRA', 'QRO', 'CP-6821', 'SUCURSAL', 46, 1, NULL),
  ('250', 'CIUDAD DEL SOL', 'Coronel', 'CIUDAD DEL SOL', 'QRO', 'CP-6821', 'SUCURSAL', 43, 1, NULL),
  ('251', 'MILENIO 3', 'Coronel', 'MILENIO 3', 'QRO', 'CP-6821', 'SUCURSAL', 44, 1, NULL),
  ('252', 'PROL PASTEUR', 'Coronel', 'PROL PASTEUR', 'QRO', 'CP-6821', 'SUCURSAL', 45, 1, NULL),
  ('253', 'VALLE DIAMANTE', 'Coronel', 'VALLE DIAMANTE', 'QRO', 'CP-6821', 'SUCURSAL', 47, 1, NULL),
  ('254', 'VISTA REAL', 'Coronel', 'VISTA REAL', 'QRO', 'CP-6821', 'SUCURSAL', 50, 1, NULL),
  ('255', 'VALLE SANTIAGO', 'Coronel', 'VALLE SANTIAGO', 'QRO', 'CP-6821', 'SUCURSAL', 48, 1, NULL),
  ('257', 'SAUCES 2', 'Coronel', 'SAUCES 2', 'QRO', 'CP-6821', 'SUCURSAL', 49, 1, NULL),
  ('258', 'LOS HEROES', 'Coronel', 'LOS HEROES', 'QRO', 'CP-6821', 'SUCURSAL', 51, 1, NULL),
  ('259', 'RINCONES MARQUES', 'Coronel', 'RINCONES MARQUES', 'QRO', 'CP-6821', 'SUCURSAL', 52, 1, NULL),
  ('260', 'VERONA', 'Coronel', 'VERONA', 'QRO', 'CP-6821', 'SUCURSAL', 53, 1, NULL),
  ('261', 'Palmares', '', 'Palmares', 'QRO', 'CP-6821', 'SUCURSAL', 81, 1, NULL),
  ('262', 'REAL SOLARE', 'Coronel', 'REAL SOLARE', 'QRO', 'CP-6821', 'SUCURSAL', 54, 1, NULL),
  ('263', 'CIUDAD SOL DOS', 'Coronel', 'CIUDAD SOL DOS', 'QRO', 'CP-6821', 'SUCURSAL', 55, 1, NULL),
  ('264', 'SANTUARIOS', 'Coronel', 'SANTUARIOS', 'QRO', 'CP-6821', 'SUCURSAL', 56, 1, NULL),
  ('265', 'SAN MIGUEL 2', 'Coronel', 'SAN MIGUEL 2', 'QRO', 'CP-6821', 'SUCURSAL', 60, 1, NULL),
  ('266', 'LOS OLVERA', 'Coronel', 'LOS OLVERA', 'QRO', 'CP-6821', 'SUCURSAL', 57, 1, NULL),
  ('267', 'REAL DEL BOSQUE', 'Coronel', 'REAL DEL BOSQUE', 'QRO', 'CP-6821', 'SUCURSAL', 58, 1, NULL),
  ('268', 'LOS ALCANFORES', 'Coronel', 'LOS ALCANFORES', 'QRO', 'CP-6821', 'SUCURSAL', 59, 1, NULL),
  ('269', 'SAN ISIDRO', 'Coronel', 'SAN ISIDRO', 'QRO', 'CP-6821', 'SUCURSAL', 61, 1, NULL),
  ('270', 'ATELIER', 'Coronel', 'ATELIER', 'QRO', 'CP-6821', 'SUCURSAL', 62, 1, NULL),
  ('271', 'TECNOLOGICO', 'Coronel', 'TECNOLOGICO', 'QRO', 'CP-6821', 'SUCURSAL', 63, 1, NULL),
  ('272', 'CANDILES 2', 'Coronel', 'CANDILES 2', 'QRO', 'CP-6821', 'SUCURSAL', 64, 1, NULL),
  ('273', 'EL REFUGIO 2', 'Coronel', 'EL REFUGIO 2', 'QRO', 'CP-6821', 'SUCURSAL', 65, 1, NULL),
  ('274', 'EL JACAL', 'Coronel', 'EL JACAL', 'QRO', 'CP-6821', 'SUCURSAL', 66, 1, NULL),
  ('275', 'JARDINES HDA(La Joya)', 'Coronel', 'JARDINES HDA', 'QRO', 'CP-6821', 'SUCURSAL', 67, 1, NULL),
  ('277', 'EL SOL', 'Coronel', 'EL SOL', 'QRO', 'CP-6821', 'SUCURSAL', 68, 1, NULL),
  ('278', 'PLAZA CANDILES', 'Coronel', 'PLAZA CANDILES', 'QRO', 'CP-6821', 'SUCURSAL', 69, 1, NULL),
  ('279', 'LOS HUERTOS', 'Coronel', 'LOS HUERTOS', 'QRO', 'CP-6821', 'SUCURSAL', 70, 1, NULL),
  ('280', 'CIMATARIO', 'Coronel', 'CIMATARIO', 'QRO', 'CP-6821', 'SUCURSAL', 71, 1, NULL),
  ('281', 'PLATON', 'Coronel', 'PLATON', 'QRO', 'CP-6821', 'SUCURSAL', 72, 1, NULL),
  ('282', 'PIRAMIDES', 'Coronel', 'PIRAMIDES', 'QRO', 'CP-6821', 'SUCURSAL', 73, 1, NULL),
  ('283', 'ZIBATA', 'Coronel', 'ZIBATA', 'QRO', 'CP-6821', 'SUCURSAL', 74, 1, NULL),
  ('284', 'JURIQUILLA II', 'Coronel', 'JURIQUILLA II', 'QRO', 'CP-6821', 'SUCURSAL', 75, 1, NULL),
  ('285', 'ZAKIA', 'Coronel', 'ZAKIA', 'QRO', 'CP-6821', 'SUCURSAL', 76, 1, NULL),
  ('286', 'PUERTA NAVARRA', 'Coronel', 'PUERTA NAVARRA', 'QRO', 'CP-6821', 'SUCURSAL', 77, 1, NULL),
  ('287', 'PEDRO ESCOBEDO', 'Coronel', 'PEDRO ESCOBEDO', 'QRO', 'CP-6821', 'SUCURSAL', 78, 1, NULL),
  ('288', 'GEOPLAZAS', 'Coronel', 'GEOLPLAZAS', 'QRO', 'CP-6821', 'SUCURSAL', 79, 1, NULL),
  ('289', 'CANDILES III', 'Coronel', 'CANDILES III', 'QRO', 'CP-6821', 'SUCURSAL', 80, 1, NULL),
  ('290', 'PEDRO ESCOBEDO II', 'Coronel', 'PEDRO ESCOBEDO II', 'QRO', 'CP-6821', 'SUCURSAL', 82, 1, NULL),
  ('291', 'PLAZA BELEN', 'Coronel', 'PLAZA BELEN', 'QRO', 'CP-6821', 'SUCURSAL', 83, 1, NULL),
  ('292', 'FUENTES DE BALVANERA', 'Coronel', 'FUENTES DE BALVANERA', 'QRO', 'CP-6821', 'SUCURSAL', 84, 1, NULL),
  ('293', 'REFUGIO III', 'Coronel', 'REFIGIO III', 'QRO', 'CP-6821', 'SUCURSAL', 85, 1, NULL),
  ('294', 'LA GLORIA', 'Coronel', 'LA GLORIA', 'QRO', 'CP-6821', 'SUCURSAL', 86, 1, NULL),
  ('302', 'SAN MIGUEL DE ALLENDE III', 'Coronel', 'SAN MIGUEL DE ALLENDE III', 'QRO', 'CP-6821', 'SUCURSAL', 87, 1, NULL),
  ('303', 'SAN JUAN DEL RIO', 'Coronel', 'SAN JUAN DEL RIO', 'QRO', 'CP-6821', 'SUCURSAL', 88, 1, NULL),
  ('304', 'Pueblito', 'Coronel', 'Pueblito', 'QRO', 'CP-6821', 'SUCURSAL', 89, 1, NULL),
  ('305', 'Sombrerete', 'Coronel', 'Sombrerete', 'QRO', 'CP-6821', 'SUCURSAL', 90, 1, NULL),
  ('306', 'Plaza naciones', 'Coronel', 'Plaza naciones', 'QRO', 'CP-6821', 'SUCURSAL', 91, 1, NULL),
  ('307', 'Lomas Calle 27', 'Coronel', 'Lomas Calle 27', 'QRO', 'CP-6821', 'SUCURSAL', 92, 1, NULL),
  ('308', 'Niños Heroes', 'Coronel', 'Niños Heroes', 'QRO', 'CP-6821', 'SUCURSAL', 93, 1, NULL),
  ('309', 'La Negreta', 'Coronel', 'La Negreta', 'QRO', 'CP-6821', 'SUCURSAL', 94, 1, NULL),
  ('310', 'Villas del Refugio', 'Coronel', 'Villas del Refugio', 'QRO', 'CP-6821', 'SUCURSAL', 95, 1, NULL),
  ('311', 'Loma Bonita', 'Coronel', 'Loma Bonita', 'QRO', 'CP-6821', 'SUCURSAL', 98, 1, NULL),
  ('312', 'Menchaca', 'Coronel', 'Menchaca', 'QRO', 'CP-6821', 'SUCURSAL', 99, 1, NULL),
  ('313', 'Garibaldi', 'Coronel', 'Garibaldi', 'QRO', 'CP-6821', 'SUCURSAL', NULL, 1, NULL),
  ('314', 'Xentric', 'Coronel', 'Xentric', 'QRO', 'CP-6821', 'SUCURSAL', NULL, 1, NULL),
  ('315', 'Burocrata', 'Coronel', 'Burocrata', 'QRO', 'CP-6821', 'SUCURSAL', 100, 1, NULL),
  ('316', 'Mileniio 100', 'Coronel', 'Milenio100', 'QRO', 'CP-6821', 'SUCURSAL', 101, 1, NULL),
  ('317', 'Tequisquiapan', 'Coronel', 'Tequis', 'QRO', 'CP-6821', 'SUCURSAL', NULL, 1, NULL),
  ('318', 'LOMAS CALLE 25', 'Coronel', '', 'QRO', 'CP-6821', 'SUCURSAL', 102, 1, NULL),
  ('319', 'Privada juriquilla', 'Coronel', 'Privada juriquilla', 'QRO', 'CP-6821', 'SUCURSAL', 104, 1, NULL),
  ('320', 'Colinas', 'Coronel', 'Colinas', 'QRO', 'CP-6821', 'SUCURSAL', 105, 1, NULL),
  ('321', 'La Popular', 'Coronel', 'La Popular', 'QRO', 'CP-6821', 'SUCURSAL', 106, 1, NULL),
  ('322', 'Santa Fe', 'Coronel', 'Tienda nueva 1', 'QRO', 'CP-6821', 'SUCURSAL', 107, 1, NULL),
  ('323', 'Colonia Cimatario', 'Coronel', 'Tienda nueva 2', 'QRO', 'CP-6821', 'SUCURSAL', 108, 1, NULL),
  ('324', 'Plaza el Roble SJR', 'Coronel', 'Tienda nueva 3', 'QRO', 'CP-6821', 'SUCURSAL', 110, 1, NULL),
  ('325', 'Av Corregidora Norte', 'Coronel', 'Tienda nueva 4', 'QRO', 'CP-6821', 'SUCURSAL', 109, 1, NULL),
  ('326', 'El Condado', 'Coronel', 'Tienda nueva 5', 'QRO', 'CP-6821', 'SUCURSAL', 111, 1, NULL),
  ('327', 'El Rocio', 'Coronel', 'Tienda nueva 6', 'QRO', 'CP-6821', 'SUCURSAL', 112, 1, NULL),
  ('328', 'Pueblo Jurica', 'Coronel', 'Tienda nueva 7', 'QRO', 'CP-6821', 'SUCURSAL', 113, 1, NULL),
  ('329', 'Zakia Zizana', 'Coronel', 'Tienda nueva 8', 'QRO', 'CP-6821', 'SUCURSAL', 114, 1, NULL),
  ('330', 'Ejido San Miguel', 'Coronel', 'Tienda Nueva 9', 'QRO', 'CP-6821', 'SUCURSAL', 115, 1, NULL),
  ('331', 'Marques Queretano', 'Coronel', 'Tienda Nueva 10', 'QRO', 'CP-6821', 'SUCURSAL', 116, 1, NULL),
  ('332', 'Loarca II', 'Coronel', 'Tienda Nueva 11', 'QRO', 'CP-6821', 'SUCURSAL', 117, 1, NULL),
  ('333', 'San Jose el Alto', 'Coronel', 'Tienda Nueva 12', 'QRO', 'CP-6821', 'SUCURSAL', 118, 1, NULL),
  ('334', 'Las Aguilas SJR', 'Coronel', 'Tienda Nueva 13', 'QRO', 'CP-6821', 'SUCURSAL', 119, 1, NULL),
  ('335', 'Plaza Rioma Cd del Sol', 'Coronel', 'Tienda Nueva 14', 'QRO', 'CP-6821', 'SUCURSAL', 120, 1, NULL),
  ('336', 'Salitre', 'Coronel', 'Tienda Nueva 15', 'QRO', 'CP-6821', 'SUCURSAL', 121, 1, NULL),
  ('338', 'Deportivo Reforma', 'Coronel', 'Tienda Nueva 16', 'QRO', 'CP-6821', 'SUCURSAL', 122, 1, NULL);


-- Hub Central CHC - usuario administrador de aplicación
-- Usuario: admin
-- Contraseña inicial: B1Admin

SET NAMES utf8mb4;
USE hubcentral_chc;

INSERT INTO users (username, password_hash, full_name, role, is_active)
VALUES ('admin', 'scrypt$16384$8$1$FVSEnB8XviQhva1/00Z5wg==$IO8vHWeQBaseJUxd07bpE8vJqhhs/ndccOR6/aczHJS2I+5ZnNywPnYB5k3v5yVwOCwbFdaiD8vXoNkSE5njJA==', 'Administrador CHC', 'admin', 1)
ON DUPLICATE KEY UPDATE
  password_hash = VALUES(password_hash),
  full_name = VALUES(full_name),
  role = VALUES(role),
  is_active = VALUES(is_active);
