-- Hub Central CHC - poblar ubicaciones
-- Se usan los enlaces de Google Maps compartidos; este seed no depende de coordenadas.

SET NAMES utf8mb4;
USE hubcentral_chc;

DELETE FROM locations;

INSERT INTO locations
  (id, branch_number, store_type, name, municipality, maps_url, status, is_pending, is_active, notes)
VALUES
  (1, 1, 'HC', 'Abastos', 'Querétaro', 'https://maps.app.goo.gl/dDL8HcPvFxK6qACQ6', 'Activa', 0, 1, NULL),
  (2, 2, 'HC', 'Carrillo', 'Querétaro', 'https://maps.app.goo.gl/b5We3ZAkcW82Sybf7', 'Activa', 0, 1, NULL),
  (3, 3, 'HC', 'Sauces', 'Querétaro', 'https://maps.app.goo.gl/3vo2RKxqXxsdKdQ97', 'Activa', 0, 1, NULL),
  (4, 4, 'HC', 'Presidentes', 'Querétaro', 'https://maps.app.goo.gl/mR3859iWoC9uupyp7', 'Activa', 0, 1, NULL),
  (5, 5, 'HC', 'San Roque', 'Querétaro', 'https://maps.app.goo.gl/4XjjshWSaiJ68kgs9', 'Activa', 0, 1, NULL),
  (6, 6, 'HC', 'Satelite', 'Querétaro', 'https://maps.app.goo.gl/MafEGGf2djKBkGaQ9', 'Activa', 0, 1, NULL),
  (7, 7, 'HC', 'Plazas del Sol', 'Querétaro', 'https://maps.app.goo.gl/QqZpuiaZXJYfwE1UA', 'Activa', 0, 1, NULL),
  (8, 8, 'HC', 'Pie de la cuesta 1', 'Querétaro', 'https://maps.app.goo.gl/ZVNMPNjGwLtaGLPm8', 'Activa', 0, 1, NULL),
  (9, 9, 'HC', 'Lomas del Marqués', 'Querétaro', 'https://maps.app.goo.gl/69996JWu3QjMkZDV6', 'Activa', 0, 1, NULL),
  (10, 10, 'HC', 'Cerrito Colorado', 'Querétaro', 'https://maps.app.goo.gl/baKpvGL4bEnM7q137', 'Activa', 0, 1, NULL),
  (11, 11, 'HC', 'Andadores', 'Querétaro', 'https://maps.app.goo.gl/yECTzBpzXZLsntJo9', 'Activa', 0, 1, NULL),
  (12, 12, 'HC', 'Reforma Agraria', 'Querétaro', 'https://maps.app.goo.gl/ircjPvYJHqRCNGSMA', 'Activa', 0, 1, NULL),
  (13, 13, 'HC', 'Tintero 1', 'Querétaro', 'https://maps.app.goo.gl/ZJ6s1dD7izuuSY4N8', 'Activa', 0, 1, NULL),
  (14, 14, 'HC', 'Tejeda 1', 'Corregidora', 'https://maps.app.goo.gl/ks24XL6kT1umV7st6', 'Activa', 0, 1, NULL),
  (15, 15, 'HC', 'Satelite 2', 'Querétaro', 'https://maps.app.goo.gl/H1NvfVg7qkKN1hV28', 'Activa', 0, 1, NULL),
  (16, 16, 'HC', 'Ensueño', 'Querétaro', 'https://maps.app.goo.gl/VmGVPMG5bRRcWDBB8', 'Activa', 0, 1, NULL),
  (17, 17, 'HC', 'Candiles 1', 'Corregidora', 'https://maps.app.goo.gl/uuEfC5axWFDUm2dn7', 'Activa', 0, 1, NULL),
  (18, 18, 'HC', 'Cerrito Colorado 2', 'Querétaro', 'https://maps.app.goo.gl/kBJskpWz4bFGuBam9', 'Activa', 0, 1, NULL),
  (19, 19, 'HC', 'Tejeda 2', 'Corregidora', 'https://maps.app.goo.gl/krc1MZEFUdvfh5426', 'Activa', 0, 1, NULL),
  (20, 20, 'HC', 'Pie de la cuesta 2', 'Querétaro', 'https://maps.app.goo.gl/kdT9kEyT63nPQvFE8', 'Activa', 0, 1, NULL),
  (21, 21, 'HC', 'Paseo San Miguel', 'Querétaro', 'https://maps.app.goo.gl/5yJGhKBsheP3MbS59', 'Activa', 0, 1, NULL),
  (22, 22, 'HC', 'La pradera 2', 'El Marqués', 'https://maps.app.goo.gl/QxsaGmPa3vNyrtHV9', 'Activa', 0, 1, NULL),
  (23, 23, 'HC', 'Loarca', 'Querétaro', 'https://maps.app.goo.gl/kh78LgTuaFy2GgCz8', 'Activa', 0, 1, NULL),
  (24, 24, 'HC', 'San Miguel de Allende 1', 'San Miguel Allende', 'https://maps.app.goo.gl/74zSHRm1G5joSPqK8', 'Activa', 0, 1, NULL),
  (25, 25, 'HC', 'San Juan de Letrán', 'Querétaro', 'https://maps.app.goo.gl/DeJxcBoyC3SuFui9A', 'Activa', 0, 1, NULL),
  (26, 26, 'HC', 'Cerrito Colorado 3', 'Querétaro', 'https://maps.app.goo.gl/RveQYBHRxpLJJefA6', 'Activa', 0, 1, NULL),
  (27, 27, 'HC', 'San Pablo', 'Querétaro', 'https://maps.app.goo.gl/H45uxbaBR11HAfBe9', 'Activa', 0, 1, NULL),
  (28, 28, 'HC', 'La Pradera 1', 'El Marqués', 'https://maps.app.goo.gl/5Em7mZiTPePjwAQXA', 'Activa', 0, 1, NULL),
  (29, 29, 'HC', 'Campo Militar', 'Querétaro', 'https://maps.app.goo.gl/14c63nWwxGqYR9Ga8', 'Activa', 0, 1, NULL),
  (30, 30, 'HC', 'Hacienda la cruz', 'El Marqués', 'https://maps.app.goo.gl/BxhxKpVpqUYbkcsc8', 'Activa', 0, 1, NULL),
  (31, 31, 'HC', 'Miranda', 'El Marqués', 'https://maps.app.goo.gl/bFnrAyoYHkDD5LV18', 'Activa', 0, 1, NULL),
  (32, 32, 'MC', 'El Mirador', 'El Marqués', 'https://maps.app.goo.gl/9MYxa4wr2vwucY7x8', 'Activa', 0, 1, NULL),
  (33, 33, 'HC', 'Insurgentes', 'Querétaro', 'https://maps.app.goo.gl/tYVrPLuk3pTxpUfY6', 'Activa', 0, 1, NULL),
  (34, 34, 'HC', 'Paseos del Pedregal', 'Querétaro', 'https://maps.app.goo.gl/rC5UhiACmWXxUg5p7', 'Activa', 0, 1, NULL),
  (35, 35, 'HC', 'Juriquilla 1', 'Querétaro', 'https://maps.app.goo.gl/M8hc3bEHBRSDExCv9', 'Activa', 0, 1, NULL),
  (36, 36, 'HC', 'Real de la Loma', 'Querétaro', 'https://maps.app.goo.gl/UNGemGQEbtb62i9T9', 'Activa', 0, 1, NULL),
  (37, 37, 'HC', 'Av de la luz', 'Querétaro', 'https://maps.app.goo.gl/yNwSbCQkrT9NxN8S6', 'Activa', 0, 1, NULL),
  (38, 38, 'HC', 'Viñedos', 'Querétaro', 'https://maps.app.goo.gl/arZdz9vttxzzKioT9', 'Activa', 0, 1, NULL),
  (39, 39, 'HC', 'Santa María', 'Querétaro', 'https://maps.app.goo.gl/JUaVamRftQzoTUURA', 'Activa', 0, 1, NULL),
  (40, 40, 'HC', 'Tintero 2 ( Ex hacienda tintero )', 'Querétaro', 'https://maps.app.goo.gl/N4az5tEuZJ2ASS7y6', 'Activa', 0, 1, NULL),
  (41, 41, 'HC', 'El Refugio 1', 'Querétaro', 'https://maps.app.goo.gl/VTjegxkpQNv3vrBc6', 'Activa', 0, 1, NULL),
  (42, 42, 'HC', 'Villas de Santiago', 'Querétaro', 'https://maps.app.goo.gl/eZ1y3ZBj2jLbWf8v5', 'Activa', 0, 1, NULL),
  (43, 43, 'HC', 'Ciudad del Sol', 'Querétaro', 'https://maps.app.goo.gl/abfhH2QSvCeGUm6H9', 'Activa', 0, 1, NULL),
  (44, 44, 'HC', 'Milenio', 'Querétaro', 'https://maps.app.goo.gl/8azbznYKAhzrz9CR7', 'Activa', 0, 1, NULL),
  (45, 45, 'HC', 'Prol Pasteur', 'Querétaro', 'https://maps.app.goo.gl/x7My78cWL8gwPTNw8', 'Activa', 0, 1, NULL),
  (46, 46, 'HC', 'Sonterra', 'Querétaro', 'https://maps.app.goo.gl/RAMDqLxXn1XwzNGy8', 'Activa', 0, 1, NULL),
  (47, 47, 'HC', 'Valle Diamante', 'Corregidora', 'https://maps.app.goo.gl/9wkvukrBb8AYGcap8', 'Activa', 0, 1, NULL),
  (48, 48, 'HC', 'Valle de Santiago', 'Querétaro', 'https://maps.app.goo.gl/5oeybsSr8Rs8oFCG9', 'Activa', 0, 1, NULL),
  (49, 49, 'HC', 'Sauces 2', 'Querétaro', 'https://maps.app.goo.gl/JTbycfr2kFCPekdY7', 'Activa', 0, 1, NULL),
  (50, 50, 'HC', 'Vista Real', 'Corregidora', 'https://maps.app.goo.gl/wb22nGFh3BUgmKMh8', 'Activa', 0, 1, NULL),
  (51, 51, 'HC', 'Los Héroes', 'El Marqués', 'https://maps.app.goo.gl/PT1Nr8edBjrwSkgZ7', 'Activa', 0, 1, NULL),
  (52, 52, 'HC', 'Rincones del Marqués', 'El Marqués', 'https://maps.app.goo.gl/SRoQPnVHWKLTQqUq6', 'Activa', 0, 1, NULL),
  (53, 53, 'HC', 'Puerta Verona', 'Querétaro', 'https://maps.app.goo.gl/KbtKVRaZmWuXgoiP8', 'Activa', 0, 1, NULL),
  (54, 54, 'HC', 'Real Solare', 'El Marqués', 'https://maps.app.goo.gl/w8Y3tmT34sUjtY119', 'Activa', 0, 1, NULL),
  (55, 55, 'HC', 'Ciudad del Sol 2', 'Querétaro', 'https://maps.app.goo.gl/Y1XEh6DL93ixqYCK6', 'Activa', 0, 1, NULL),
  (56, 56, 'HC', 'Santuario', 'Corregidora', 'https://maps.app.goo.gl/gjsodumxetbug6Ac6', 'Activa', 0, 1, NULL),
  (57, 57, 'HC', 'Los Olvera', 'Corregidora', 'https://maps.app.goo.gl/414YsCvuoxKfPbkSA', 'Activa', 0, 1, NULL),
  (58, 58, 'HC', 'Real del Bosque', 'Corregidora', 'https://maps.app.goo.gl/DiVzXBEMVmb8ZYvQ9', 'Activa', 0, 1, NULL),
  (59, 59, 'HC', 'Alcanfores', 'Querétaro', 'https://maps.app.goo.gl/Ty2GwUtTyMLVPgRMA', 'Activa', 0, 1, NULL),
  (60, 60, 'HC', 'San Miguel de Allende 2', 'San Miguel Allende', 'https://maps.app.goo.gl/E4vchv9gk9RD9tgi7', 'Activa', 0, 1, NULL),
  (61, 61, 'HC', 'San Isidro', 'Querétaro', 'https://maps.app.goo.gl/X3prNJoZtbVHetfH6', 'Activa', 0, 1, NULL),
  (62, 62, 'MC', 'Plaza Atelier', 'Querétaro', 'https://maps.app.goo.gl/bSo43CQqGpfdr5bR7', 'Activa', 0, 1, NULL),
  (63, 63, 'HC', 'Tecnologico', 'Querétaro', 'https://maps.app.goo.gl/kSTzP2X3yugh7p2a8', 'Activa', 0, 1, NULL),
  (64, 64, 'HC', 'Candiles 2', 'Corregidora', 'https://maps.app.goo.gl/PPXAEfA6ZCcFyizA8', 'Activa', 0, 1, NULL),
  (65, 65, 'HC', 'El Refugio 2', 'Querétaro', 'https://maps.app.goo.gl/k2DbbbkBgx4ENSQJ8', 'Activa', 0, 1, NULL),
  (66, 66, 'HC', 'Jacal', 'Corregidora', 'https://maps.app.goo.gl/UUu4YgHaGcoJ3PC2A', 'Activa', 0, 1, NULL),
  (67, 67, 'HC', 'Jardines de la hacienda', 'Querétaro', 'https://maps.app.goo.gl/kk2uff7U9Efdypu98', 'Activa', 0, 1, NULL),
  (68, 68, 'HC', 'Av del sol', 'Querétaro', 'https://maps.app.goo.gl/7J8yCncrWhqomXrn6', 'Activa', 0, 1, NULL),
  (69, 69, 'HC', 'Plaza Candiles', 'Corregidora', 'https://maps.app.goo.gl/yJduHX5EbW2EfM396', 'Activa', 0, 1, NULL),
  (70, 70, 'HC', 'Los huertos', 'Querétaro', 'https://maps.app.goo.gl/hr1x4h2PokiTnYSZ6', 'Activa', 0, 1, NULL),
  (71, 71, 'HC', 'Av Cimatario', 'Querétaro', 'https://share.google/uWBjtvKQVwiMIcS8Y', 'Activa', 0, 1, NULL),
  (72, 72, 'HC', 'Platón', 'Querétaro', 'https://maps.app.goo.gl/UYP7qGgLkYNMAqWLA', 'Activa', 0, 1, NULL),
  (73, 73, 'HC', 'Piramides', 'Corregidora', 'https://maps.app.goo.gl/zZXaQbGNjQAeKEuA7', 'Activa', 0, 1, NULL),
  (74, 74, 'MC', 'Zibata 1', 'El Marqués', 'https://maps.app.goo.gl/F4pRHM6TGjvbjH5k8', 'Activa', 0, 1, NULL),
  (75, 75, 'HC', 'Juriquilla 2', 'Querétaro', 'https://maps.app.goo.gl/Ko2ARVWhLYuNQLGz6', 'Activa', 0, 1, NULL),
  (76, 76, 'MC', 'Zakia', 'El Marqués', 'https://maps.app.goo.gl/6f6bFsvzfyDPHKCEA', 'Activa', 0, 1, NULL),
  (77, 77, 'HC', 'Puerta Navarra', 'Querétaro', 'https://maps.app.goo.gl/xFd4AQjVmJWXctWp8', 'Activa', 0, 1, NULL),
  (78, 78, 'HC', 'Pedro Escobedo', 'Pedro Escobedo', 'https://maps.app.goo.gl/svrpqisjUtpWTghh8', 'Activa', 0, 1, NULL),
  (79, 79, 'HC', 'Geo plazas', 'Querétaro', 'https://maps.app.goo.gl/xW9VseDQiyooSSuAA', 'Activa', 0, 1, NULL),
  (80, 80, 'HC', 'Candiles 3', 'Corregidora', 'https://maps.app.goo.gl/i6GnqAkwj73UfxY48', 'Activa', 0, 1, NULL),
  (81, 81, 'HC', 'Palmares', 'Querétaro', 'https://maps.app.goo.gl/Tar4zuQRwSuMCvPq7', 'Activa', 0, 1, NULL),
  (82, 82, 'HC', 'Pedro Escobedo 2', 'Pedro Escobedo', 'https://maps.app.goo.gl/5A8xtX7nkFeYh5Mx9', 'Activa', 0, 1, NULL),
  (83, 83, 'HC', 'Plaza Belén', 'Querétaro', 'https://maps.app.goo.gl/dQUFAQrjLTSvhCD27', 'Activa', 0, 1, NULL),
  (84, 84, 'HC', 'Fuentes de Balvanera', 'Apaseo el Grande', 'https://maps.app.goo.gl/DGRgXZxjnRR1ZmccA', 'Activa', 0, 1, NULL),
  (85, 85, 'HC', 'El Refugio 3', 'Querétaro', 'https://maps.app.goo.gl/HRfdyKWkr2qwLMuP6', 'Activa', 0, 1, NULL),
  (86, 86, 'HC', 'La Gloria', 'Querétaro', 'https://maps.app.goo.gl/uA4k61Jyb8t4ZZbT6', 'Activa', 0, 1, NULL),
  (87, 87, 'HC', 'San Miguel de Allende 3', 'San Miguel Allende', 'https://maps.app.goo.gl/roEyD489qcqVxphX8', 'Activa', 0, 1, NULL),
  (88, 88, 'HC', 'Real de San Isidro San Juan del Río', 'San Juan del Río', 'https://maps.app.goo.gl/jH2guewiY7iMckuY9', 'Activa', 0, 1, NULL),
  (89, 89, 'HC', 'El pueblito', 'Corregidora', 'https://maps.app.goo.gl/x9SQrYrhGHkRN2fWA', 'Activa', 0, 1, NULL),
  (90, 90, 'HC', 'Sombrerete', 'Querétaro', 'https://maps.app.goo.gl/8RMavPazYtZ721fD7', 'Activa', 0, 1, NULL),
  (91, 91, 'HC', 'Plaza Naciones', 'Querétaro', 'https://maps.app.goo.gl/oa8sQrRzQYmfaQnf7', 'Activa', 0, 1, NULL),
  (92, 92, 'HC', 'Lomas Calle 27', 'Querétaro', 'https://maps.app.goo.gl/NRGg4LqKMN63ncWk6', 'Activa', 0, 1, NULL),
  (93, 93, 'HC', 'Niños Héroes', 'Querétaro', 'https://maps.app.goo.gl/9XGLoij5TvDmFNVw6', 'Activa', 0, 1, NULL),
  (94, 94, 'HC', 'La negreta', 'Corregidora', 'https://maps.app.goo.gl/2Dc4tTS6sZEBjmSu8', 'Activa', 0, 1, NULL),
  (95, 95, 'HC', 'Villas del Refugio', 'El Marqués', 'https://maps.app.goo.gl/WntGWX7HYKnpfjX98', 'Activa', 0, 1, NULL),
  (96, 96, 'MC', 'Zibata 2', 'El Marqués', 'https://maps.app.goo.gl/ccGefjr5aoCVmj1q6', 'Activa', 0, 1, NULL),
  (97, 97, 'HC', 'San Miguel de Allende 4', 'San Miguel Allende', 'https://maps.app.goo.gl/ZCQ3f88fYjPvdTiS9', 'Activa', 0, 1, NULL),
  (98, 98, 'HC', 'Loma Bonita', 'Querétaro', 'https://maps.app.goo.gl/TeQroH5nUGpgMifDA', 'Activa', 0, 1, NULL),
  (99, 99, 'HC', 'Menchaca', 'Querétaro', 'https://maps.app.goo.gl/t6SrKqvwgeHu5sPX6', 'Activa', 0, 1, NULL),
  (100, 100, 'HC', 'Burócrata', 'Querétaro', 'https://maps.app.goo.gl/9CYfmxoh4osomwai6', 'Activa', 0, 1, NULL),
  (101, 101, 'HC', 'Milenio #100', 'Querétaro', 'https://maps.app.goo.gl/xDKmDD2b8mWFKWNH9', 'Activa', 0, 1, NULL),
  (102, 102, 'HC', 'Lomas Calle 25', 'Querétaro', 'https://maps.app.goo.gl/hRjVZijeNyCjZbbi9', 'Activa', 0, 1, NULL),
  (104, 104, 'HC', 'Privada Juriquilla', 'Querétaro', 'https://maps.app.goo.gl/tvdiPUfNidutnMrz8', 'Activa', 0, 1, NULL),
  (105, 105, 'HC', 'Colinas del Sol', 'Corregidora', 'https://maps.app.goo.gl/ugFwdNh8GyGwCEsd7', 'Activa', 0, 1, NULL),
  (106, 106, 'HC', 'La popular', 'Querétaro', 'https://maps.app.goo.gl/C4CWeTerXud3ifcz7', 'Activa', 0, 1, NULL),
  (107, 107, 'HC', 'Santa Fe', 'Querétaro', 'https://maps.app.goo.gl/o6kofCYJUb3PqcRZ7', 'Activa', 0, 1, NULL),
  (108, 108, 'HC', 'Cimatario Panteón', 'Querétaro', 'https://maps.app.goo.gl/NdvDGZFCaZBktSvC9', 'Activa', 0, 1, NULL),
  (109, 109, 'HC', 'Corregidora Centro', 'Querétaro', 'https://maps.app.goo.gl/2J9ymN1Kq9SfCh3v5', 'Activa', 0, 1, NULL),
  (110, 110, 'HC', 'San Juan del Río 2 El Roble', 'San Juan del Río', 'https://maps.app.goo.gl/Wta1bnsjFFGrbxoj7', 'Activa', 0, 1, NULL),
  (111, 111, 'HC', 'El Condado', 'Corregidora', 'https://maps.app.goo.gl/EppaBVzNuarvKkgy5', 'Activa', 0, 1, NULL),
  (112, 112, 'HC', 'El Rocío', 'Querétaro', 'https://maps.app.goo.gl/2m4C2FxuRMaAK4USA', 'Activa', 0, 1, NULL),
  (113, 113, 'HC', 'Pueblo de Jurica', 'Querétaro', 'https://maps.app.goo.gl/7sCtmi2kGVJPE3gVA', 'Activa', 0, 1, NULL),
  (114, 114, 'MC', 'Zakia Zizana', 'El Marqués', 'https://maps.app.goo.gl/XoSwnpnLvEpC9Pc1A', 'Activa', 0, 1, NULL),
  (115, 115, 'HC', 'Ejido San Miguel', 'Querétaro', 'https://maps.app.goo.gl/Ua1qbJ9SCdzPed297', 'Activa', 0, 1, NULL),
  (116, 116, 'HC', 'El marqués queretano', 'Querétaro', 'https://maps.app.goo.gl/CEAdCrMtAh1ZyL8C7', 'Activa', 0, 1, NULL),
  (117, 117, 'HC', 'Loarca 2', 'Querétaro', 'https://maps.app.goo.gl/xPQsGh6BbqgM1DS79', 'Activa', 0, 1, NULL),
  (118, 118, 'HC', 'San Jose el alto 1', 'Querétaro', 'https://maps.app.goo.gl/AP52YHsMBrcLiyCh8', 'Activa', 0, 1, NULL),
  (119, 119, 'HC', 'SJR - Las Aguilas', 'San Juan del Río', 'https://maps.app.goo.gl/zZ7az4RRtgZrrL8K8', 'Activa', 0, 1, NULL),
  (120, 120, 'HC', 'Cd del sol - Plaza Rioma', 'Querétaro', 'https://maps.app.goo.gl/jaLPxAVZFhqCQZYG7', 'Activa', 0, 1, NULL),
  (121, 121, 'HC', 'El Salitre', 'Querétaro', 'https://maps.app.goo.gl/njQ9eM4SWbVbGpS8A', 'Activa', 0, 1, NULL),
  (122, 122, 'HC', 'Reforma Deportiva', 'Querétaro', 'https://maps.app.goo.gl/vHDrnoywDfrEJMov9', 'Activa', 0, 1, NULL),
  (125, 125, 'HC', 'Villas de Santiago 2', 'Querétaro', 'https://maps.app.goo.gl/vAP9i83RoDvXcfus6', 'Activa', 0, 1, NULL),
  (1001, NULL, 'HC', 'Fuentes de Balvanera 2', 'Apaseo el Grande', NULL, 'En tramite', 1, 1, 'Sucursal pendiente importada desde la página de ubicaciones.'),
  (1002, NULL, 'HC', 'La lira', 'Pedro Escobedo', NULL, 'No abierta', 1, 1, 'Sucursal pendiente importada desde la página de ubicaciones.');

ALTER TABLE locations AUTO_INCREMENT = 1003;
